version: "3.9"

services:
  api:
    build:
      context: backend/api
      dockerfile: Dockerfile
    ports:
      - ${API_OUTER_PORT}:${API_PORT}
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - ${UI_OUTER_PORT}:80
